version: '3.9'
services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: maplytic-postgis
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "maplytic_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  maplytic:
    build: .
    container_name: maplytic-app
    depends_on:
      postgis:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    restart: always

volumes:
  pgdata:
